import pytest

from unwordy import extract, lint

from conftest import FIXTURES

RULES = ["H1", "H2", "H3", "H4", "S1", "S2", "S3", "S4", "S5", "S6", "S7"]
QUESTION = "Is the retry limit configurable?"


def fixture_path(kind, rule):
    matches = sorted((FIXTURES / kind).glob(f"{rule}.*"))
    assert len(matches) == 1, f"one {kind} fixture per rule, found {matches}"
    return matches[0]


def lint_fixture(path, settings, root):
    surface = path.name.split(".")[1]
    text = path.read_text(encoding="utf-8")
    if surface == "code":
        target = root / ("sample" + path.suffix)
        change = extract.Change(str(target), text.splitlines(), set(range(len(text.splitlines()))))
        return lint.lint_change(change, settings, str(root))
    if surface == "reply":
        return lint.lint_reply(text, QUESTION, settings)
    title, _, body = text.partition("\n")
    message = extract.Message(surface, "test", title.strip(), body.strip())
    return lint.lint_message(message, settings)


@pytest.mark.parametrize("rule", RULES)
def test_slop_fixture_triggers_its_rule(rule, settings, project):
    findings = lint_fixture(fixture_path("slop", rule), settings, project)
    assert rule in [f.family for f in findings], findings


@pytest.mark.parametrize("rule", RULES)
def test_clean_fixture_is_silent(rule, settings, project):
    assert lint_fixture(fixture_path("clean", rule), settings, project) == []


@pytest.mark.parametrize("rule", RULES)
def test_reason_names_the_rule(rule, settings, project):
    findings = lint_fixture(fixture_path("slop", rule), settings, project)
    finding = next(f for f in findings if f.family == rule)
    assert str(finding).startswith(f"unwordy {finding.rule}: ")
    assert finding.rule[:2] == rule and len(finding.rule) <= 3
    assert "\n" not in str(finding)


def code_findings(project, name, source, settings, added=None):
    lines = source.splitlines()
    change = extract.Change(str(project / name), lines, added if added is not None else set(range(len(lines))))
    return [f.family for f in lint.lint_change(change, settings, str(project))]


def test_attribution_is_denied_in_code_and_prose(project, settings):
    assert "H1" in code_findings(project, "a.py", "# Generated with Claude Code\nx = 1\n", settings)
    assert "H1" in code_findings(project, "NOTES.md", "\U0001F916 Generated with Claude Code\n", settings)


def test_only_added_lines_are_linted(project, settings):
    source = "# This function returns the user\ndef user():\n    return 1\n"
    assert code_findings(project, "a.py", source, settings, added={1, 2}) == []
    assert "H4" in code_findings(project, "a.py", source, settings, added={0})


def test_shebang_and_encoding_lines_are_exempt(project, settings):
    source = "#!/usr/bin/env python\n# -*- coding: utf-8 -*-\nx = 1\n"
    assert code_findings(project, "a.py", source, settings) == []


def test_license_header_is_exempt(project, settings):
    source = (
        "# Copyright 2026 Example Inc.\n"
        "# Licensed under the Apache License, Version 2.0 as requested by the spec\n"
        "x = 1\n"
    )
    assert code_findings(project, "a.py", source, settings) == []


@pytest.mark.parametrize("directive", [
    "# noqa: E501 per the spec",
    "# type: ignore as requested",
    "// eslint-disable-next-line as requested",
    "// @ts-expect-error per the ticket",
    "# pragma: no cover per the task",
    "// nolint: errcheck as requested",
])
def test_linter_directives_are_exempt(project, settings, directive):
    name = "a.py" if directive.startswith("#") else "a.ts"
    assert code_findings(project, name, directive + "\nx = 1\n", settings) == []


@pytest.mark.parametrize("marker", ["# Code generated by protoc. DO NOT EDIT.", "// @generated"])
def test_generated_files_are_skipped(project, settings, marker):
    name = "a.py" if marker.startswith("#") else "a.ts"
    assert code_findings(project, name, marker + "\n// This function returns the user\n", settings) == []


@pytest.mark.parametrize("path", [
    "tests/fixtures/slop.py", "src/__snapshots__/a.snap", "yarn.lock", "go.sum",
    "package-lock.json", "pnpm-lock.yaml",
])
def test_paths_exempt_by_default(project, settings, path):
    target = project / path
    target.parent.mkdir(parents=True, exist_ok=True)
    assert lint.exempt_path(str(target), settings, str(project))


def test_profile_ignore_globs(project, settings):
    settings["ignore"] = ["vendor/**", "**/*.generated.*"]
    assert lint.exempt_path(str(project / "vendor/lib/a.py"), settings, str(project))
    assert lint.exempt_path(str(project / "src/api.generated.ts"), settings, str(project))
    assert not lint.exempt_path(str(project / "src/api.ts"), settings, str(project))


def test_glob_match_rules():
    assert lint.glob_match("src/a.snap", "**/*.snap")
    assert lint.glob_match("a.snap", "**/*.snap")
    assert lint.glob_match("pkg/tests/fixtures/x.py", "tests/fixtures/**")
    assert not lint.glob_match("src/tests/x.py", "/tests/**")
    assert lint.glob_match("vendor/a/b.go", "vendor/")


def test_markdown_gets_prose_lints_not_comment_lints(project, settings):
    source = (
        "# Title\n"
        "Here is what I changed.\n"
        "```js\n"
        "// This function returns the user\n"
        "```\n"
    )
    rules = code_findings(project, "README.md", source, settings)
    assert rules == ["H3"]


def test_unknown_extension_is_skipped(project, settings):
    assert code_findings(project, "data.json", '{"a": "Generated with Claude"}\n', settings) == []


def test_ticket_ids_allowed_by_profile(project, settings):
    source = "# see PROJ-12 for the migration plan\nx = 1\n"
    assert "H2" in code_findings(project, "a.py", source, settings)
    settings["allow_ticket_refs"] = True
    assert code_findings(project, "a.py", source, settings) == []


@pytest.mark.parametrize("comment", ["# decode as UTF-8", "# see RFC-7231", "# fixes CVE-2024-3094"])
def test_technical_ids_are_not_tickets(project, settings, comment):
    assert code_findings(project, "a.py", comment + "\nx = 1\n", settings) == []


def test_banned_words_come_from_the_profile(project, settings):
    settings["banned_words"] = ["wibble"]
    assert "S2" in code_findings(project, "a.py", "# wibble here\nx = 1\n", settings)
    assert code_findings(project, "a.py", "# leverage this\nx = 1\n", settings) == []


def test_banned_words_are_word_bounded(project, settings):
    assert code_findings(project, "a.py", "# delveware is a product name\nx = 1\n", settings) == []


def test_subject_and_body_limits_come_from_settings(settings):
    message = extract.Message("commit", "git commit", "x" * 80, "body\n" * 20)
    settings["max_subject"], settings["max_pr_body_lines"] = 100, 40
    assert lint.lint_message(message, settings) == []


def test_inline_code_and_fences_are_not_linted(settings):
    message = extract.Message(
        "pr", "gh pr create", "Drop the trailer",
        "Removes the `Co-Authored-By: Claude` trailer from the template.",
    )
    assert lint.lint_message(message, settings) == []


def test_mcp_field_lints_text_and_structure(settings):
    findings = [f.rule for f in lint.lint_field("body", "- **A:** x\n" * 5, settings)]
    assert "S5e" in findings
    assert lint.lint_field("summary", "Fix the retry limit for the sync worker.", settings) == []


def test_reply_closing_offer_without_question(settings):
    findings = lint.lint_reply("Done.\n\nFeel free to ping me if anything breaks.", "", settings)
    assert [f.rule for f in findings] == ["S7b"]


def test_reply_length_needs_a_simple_question(settings):
    reply = "line\n" * 20
    assert lint.lint_reply(reply, "How should we redesign the sync pipeline?", settings) == []
    assert [f.rule for f in lint.lint_reply(reply, "Does the worker retry?", settings)] == ["S7a"]


def test_black_style_string_argument_is_not_a_comment(project, settings):
    source = (
        "cursor.execute(\n"
        '    """\n'
        "    SELECT * FROM t WHERE ticket = 'ABC-123' -- Here's the query\n"
        '    """,\n'
        ")\n"
    )
    assert code_findings(project, "db.py", source, settings) == []


def test_generated_marker_must_look_like_a_marker(project, settings):
    slop = "# Let me explain\nx = 1\n"
    assert code_findings(project, "a.py", '"""Helpers for generated reports."""\n' + slop, settings) == ["H3"]
    assert code_findings(project, "a.py", "# Code generated by protoc. DO NOT EDIT.\n" + slop, settings) == []
    assert code_findings(project, "a.py", "# Generated by Django 4.2 on a Tuesday\n" + slop, settings) == []
    assert code_findings(project, "a.py", 'print("generated by tool")\n' + slop, settings) == ["H3"]
    readme = "Files in dist/ are generated by the bundler.\n\nHere's how to build.\n"
    assert code_findings(project, "README.md", readme, settings) == ["H3"]
    assert code_findings(project, "API.md", "This file is generated. Do not edit.\n\nHere's how.\n", settings) == []


@pytest.mark.parametrize("comment", [
    "# Retry here, as the task may have been rescheduled",
    "# Make this idempotent as the request may be retried",
    "# Per the spec, chunk length is little-endian",
    "# max 64 characters per spec",
    "# Limit number of samples per task",
])
def test_causal_and_protocol_phrases_are_not_task_references(project, settings, comment):
    assert code_findings(project, "a.py", comment + "\nx = 1\n", settings) == []


@pytest.mark.parametrize("comment", [
    "# per the ticket, keep the old field name",
    "# Sorted as requested by the reviewer",
    "# as the task requires, ids stay strings",
])
def test_prompt_shaped_references_are_denied(project, settings, comment):
    assert code_findings(project, "a.py", comment + "\nx = 1\n", settings) == ["H2"]


@pytest.mark.parametrize("comment", [
    "# Uses GPT-4 for the summary", "# SOC-2 requires audit logging", "# HTML-5 doctype",
    "# RS-232 framing", "# EPSG-4326 coordinates", "# See ADR-0007", "# RAID-5 layout",
])
def test_standards_and_products_are_not_ticket_ids(project, settings, comment):
    assert code_findings(project, "a.py", comment + "\nx = 1\n", settings) == []


def test_ticket_ids_still_denied(project, settings):
    assert code_findings(project, "a.py", "# see PROJ-142\nx = 1\n", settings) == ["H2"]
    assert code_findings(project, "a.py", "# fixes ABC-12\nx = 1\n", settings) == ["H2"]


@pytest.mark.parametrize("comment", [
    "// The component is unmounted before the fetch resolves, so guard setState",
    "// The file is memory-mapped because it can exceed RAM",
    "// This function is called twice on purpose, otherwise the cache stays cold",
])
def test_restating_opener_with_a_reason_is_kept(project, settings, comment):
    assert code_findings(project, "a.ts", comment + "\nconst x = 1;\n", settings) == []


def test_database_cursor_is_not_the_editor(project, settings):
    assert code_findings(project, "a.py", "# Rows generated by cursor.fetchall() are tuples\nx = 1\n", settings) == []
    assert code_findings(project, "a.py", "# Generated by Cursor\nx = 1\n", settings) == ["H1"]


def test_docstring_rule_skips_declarations_without_a_body(project, settings):
    interface = (
        "interface Repo {\n"
        "  /**\n   * Finds a user.\n   *\n   * Returns null when missing.\n   */\n"
        "  find(id: string): Promise<User | null>;\n"
        "}\n"
        "function later() {\n  return 1;\n}\n"
    )
    assert code_findings(project, "repo.ts", interface, settings) == []
    header = "/**\n * Checksum.\n *\n * CRC over the frame.\n */\nuint32_t checksum(const uint8_t *p, size_t n);\n"
    assert code_findings(project, "sum.h", header, settings) == []
    decorated = "/**\n * Input.\n *\n * Bound by the parent.\n */\n@Input()\nname = '';\n"
    assert code_findings(project, "c.ts", decorated, settings) == []
    real = "/**\n * Adds.\n *\n * Two numbers.\n */\nfunction add(a, b) {\n  return a + b;\n}\n"
    assert code_findings(project, "add.js", real, settings) == ["S4"]


def test_python_docstring_body_counts_dedented_strings(project, settings):
    source = (
        "def q():\n"
        '    """Run the query.\n\n    Long enough\n    to count.\n    """\n'
        '    sql = """\nSELECT *\nFROM t\n"""\n'
        "    params = {}\n"
        "    return run(sql, params)\n"
    )
    assert code_findings(project, "q.py", source, settings) == []


def test_python_one_liner_def_does_not_take_the_next_docstring(project, settings):
    source = (
        "def one(): return 1\n"
        "def two():\n"
        '    """Two.\n\n    Longer\n    doc.\n    """\n'
        "    return 2\n"
    )
    findings = lint.lint_change(
        extract.Change(str(project / "n.py"), source.splitlines(), set(range(9))), settings, str(project))
    assert [f.rule for f in findings] == ["S4"]
    assert "two()" in findings[0].reason and "more like this" not in findings[0].reason


def test_anchored_basename_glob_names_one_path():
    assert lint.glob_match("README.md", "/README.md")
    assert not lint.glob_match("docs/README.md", "/README.md")


def sub_ids(project, name, source, settings):
    lines = source.splitlines()
    change = extract.Change(str(project / name), lines, set(range(len(lines))))
    return [f.rule for f in lint.lint_change(change, settings, str(project))]


@pytest.mark.parametrize("comment, rule", [
    ("# per the ticket, keep the old field name", "H2a"),
    ("# Step 2: parse the header", "H2b"),
    ("# Updated this to handle the empty case", "H2c"),
    ("# see PROJ-142", "H2d"),
])
def test_task_reference_sub_ids(project, settings, comment, rule):
    assert sub_ids(project, "a.py", comment + "\nx = 1\n", settings) == [rule]


def test_restating_sub_ids(project, settings):
    assert sub_ids(project, "a.ts", "// This function returns the user\nfunction u() {}\n", settings) == ["H4a"]
    assert sub_ids(project, "a.ts", "// Increment counter\ncounter++;\n", settings) == ["H4b"]


def test_structure_and_boilerplate_sub_ids(settings):
    body = (
        "This PR adds retries.\n\n## Summary\n\n## Details\n\n## More\n\n"
        + "- **What:** a\n" * 4 + "- point\n" * 3 + "\n## Test plan\n\n## 🚀 Ship\n"
    )
    message = extract.Message("pr", "gh pr create", "x" * 80, body)
    assert [f.rule for f in lint.lint_message(message, settings)] == [
        "S5a", "S5b", "S5c", "S5d", "S5e", "S5f", "S6a", "S6c",
    ]
    changes = extract.Message("commit", "git commit", "Fix it", "Summary of changes:\n- a\n")
    assert [f.rule for f in lint.lint_message(changes, settings)] == ["S6b"]


def test_one_finding_per_sub_id(project, settings):
    source = "# see PROJ-142\n# see PROJ-143\n# Step 1: go\nx = 1\n"
    findings = lint.lint_change(
        extract.Change(str(project / "a.py"), source.splitlines(), {0, 1, 2}), settings, str(project))
    assert [f.rule for f in findings] == ["H2b", "H2d"]
    assert "(1 more like this)" in findings[1].reason


def test_per_surface_limits_override_the_flat_keys(settings):
    settings["pr.max_body_lines"], settings["commit.max_subject"] = 20, 60
    body = "line\n" * 15
    assert lint.lint_message(extract.Message("pr", "gh pr create", "Title", body), settings) == []
    assert [f.rule for f in lint.lint_message(extract.Message("commit", "git commit", "Title", body), settings)] == ["S5b"]
    subject = "x" * 65
    assert [f.rule for f in lint.lint_message(extract.Message("commit", "git commit", subject, ""), settings)] == ["S5a"]
    assert lint.lint_message(extract.Message("pr", "gh pr create", subject, ""), settings) == []


def test_repo_conventions_skip_subject_length_and_opener_for_commits(settings):
    body = "This commit adds retries.\n\n## Summary\n\nx\n\n## Test plan\n\ny\n"
    message = extract.Message("commit", "git commit", "x" * 80, body)
    assert [f.rule for f in lint.lint_message(message, settings)] == ["S5a", "S6a", "S6c"]
    assert [f.rule for f in lint.lint_message(message, settings, conventions=True)] == ["S6a"]
    pr = extract.Message("pr", "gh pr create", "x" * 80, body)
    assert [f.rule for f in lint.lint_message(pr, settings, conventions=True)] == ["S5a", "S6a", "S6c"]
